In [1]:
import numpy as np

In [2]:
l = [1,2,3,4,5]

In [4]:
arr = np.array(l)

In [5]:
type(arr)

numpy.ndarray

In [6]:
np.asarray(l)

array([1, 2, 3, 4, 5])

In [11]:
arr1 = np.array([[1,2,3] , [2,3,4]])

In [12]:
arr.ndim

1

In [13]:
arr1.ndim

2

In [14]:
arr

array([1, 2, 3, 4, 5])

In [15]:
arr1

array([[1, 2, 3],
       [2, 3, 4]])

In [17]:
mat = np.matrix(l)

In [18]:
np.asanyarray(mat)

matrix([[1, 2, 3, 4, 5]])

In [19]:
a = arr

In [20]:
a

array([1, 2, 3, 4, 5])

In [21]:
arr

array([1, 2, 3, 4, 5])

In [22]:
arr[0] = 100

In [23]:
arr

array([100,   2,   3,   4,   5])

In [24]:
b = np.copy(arr)

In [25]:
b[0] = 234

In [26]:
arr

array([100,   2,   3,   4,   5])

In [27]:
b

array([234,   2,   3,   4,   5])

In [28]:
np.fromfunction(lambda i,j : i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [29]:
np.fromfunction(lambda i,j : i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [31]:
list(i*i for i in range(5))

[0, 1, 4, 9, 16]

In [32]:
iterable = (i*i for i in range(5))

In [33]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [34]:
np.fromstring('23 34 45',sep = ' ')

array([23., 34., 45.])

In [35]:
np.fromstring('23,34,45',sep = ',')

array([23., 34., 45.])

In [36]:
arr1

array([[1, 2, 3],
       [2, 3, 4]])

In [37]:
arr.ndim

1