In [1]:
import numpy as np

In [2]:
list(range(5))

[0, 1, 2, 3, 4]

In [4]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
list(np.arange(0.4,10.4,0.2))

[0.4,
 0.6000000000000001,
 0.8000000000000002,
 1.0000000000000002,
 1.2000000000000002,
 1.4000000000000004,
 1.6000000000000005,
 1.8000000000000003,
 2.0000000000000004,
 2.2000000000000006,
 2.400000000000001,
 2.6000000000000005,
 2.8000000000000007,
 3.000000000000001,
 3.2000000000000006,
 3.400000000000001,
 3.600000000000001,
 3.800000000000001,
 4.000000000000002,
 4.200000000000001,
 4.400000000000002,
 4.600000000000001,
 4.800000000000002,
 5.000000000000002,
 5.200000000000002,
 5.400000000000002,
 5.600000000000002,
 5.8000000000000025,
 6.000000000000002,
 6.200000000000002,
 6.400000000000002,
 6.600000000000002,
 6.8000000000000025,
 7.000000000000003,
 7.200000000000003,
 7.400000000000003,
 7.600000000000003,
 7.8000000000000025,
 8.000000000000002,
 8.200000000000003,
 8.400000000000004,
 8.600000000000003,
 8.800000000000002,
 9.000000000000004,
 9.200000000000003,
 9.400000000000004,
 9.600000000000003,
 9.800000000000004,
 10.000000000000004,
 10.20000000000000

In [8]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [10]:
np.logspace(1,5,10,base=2)

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [11]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [14]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [16]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [17]:
arr = np.ones((3,4))

In [18]:
arr+5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [19]:
arr*4

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [21]:
np.empty((3,4))

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [23]:
arr1 = np.eye(5)

In [24]:
import pandas as pd

In [25]:
pd.DataFrame(arr1)

0    1    2    3    4
0  1.0  0.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0  0.0
3  0.0  0.0  0.0  1.0  0.0
4  0.0  0.0  0.0  0.0  1.0

In [26]:
np.random.rand(2,3)

array([[0.51501099, 0.60936616, 0.3630059 ],
       [0.4928577 , 0.28537968, 0.83604852]])

In [27]:
np.random.randn(2,3)

array([[ 1.05985218, -0.42026123, -0.74629279],
       [ 1.39955109,  0.44008348, -0.42576661]])

In [29]:
arr2 = np.random.randint(1,5,(3,4))

In [30]:
arr2

array([[3, 1, 3, 1],
       [2, 2, 2, 3],
       [2, 4, 1, 3]])

In [31]:
arr2.size

12

In [32]:
arr2.shape

(3, 4)

In [34]:
arr2.reshape(6,2)

array([[3, 1],
       [3, 1],
       [2, 2],
       [2, 3],
       [2, 4],
       [1, 3]])

In [35]:
arr2.shape(6,3)

TypeError: 'tuple' object is not callable

In [37]:
arr2.reshape(4,3)

array([[3, 1, 3],
       [1, 2, 2],
       [2, 3, 2],
       [4, 1, 3]])

In [38]:
arr2.reshape(2,2,3)

array([[[3, 1, 3],
        [1, 2, 2]],

       [[2, 3, 2],
        [4, 1, 3]]])

In [39]:
arr1 = np.random.randint(1,10,(5,6))

In [40]:
arr1

array([[2, 7, 2, 3, 9, 7],
       [2, 2, 5, 4, 9, 8],
       [2, 4, 1, 2, 2, 4],
       [3, 6, 9, 5, 7, 6],
       [4, 6, 8, 6, 7, 6]])

In [41]:
arr1>8

array([[False, False, False, False,  True, False],
       [False, False, False, False,  True, False],
       [False, False, False, False, False, False],
       [False, False,  True, False, False, False],
       [False, False, False, False, False, False]])

In [42]:
arr1[arr1>8]

array([9, 9, 9])

In [43]:
arr1

array([[2, 7, 2, 3, 9, 7],
       [2, 2, 5, 4, 9, 8],
       [2, 4, 1, 2, 2, 4],
       [3, 6, 9, 5, 7, 6],
       [4, 6, 8, 6, 7, 6]])

In [44]:
arr1[0]

array([2, 7, 2, 3, 9, 7])

In [45]:
arr1[0,[0,1]]

array([2, 7])

In [48]:
arr1[2:4,[2,3]]

array([[1, 2],
       [9, 5]])

In [50]:
arr1 = np.random.randint(1,3,(3,3))
arr2 = np.random.randint(1,3,(3,3))

In [51]:
arr1

array([[2, 1, 2],
       [2, 2, 1],
       [1, 2, 2]])

In [52]:
arr2

array([[2, 2, 2],
       [2, 2, 1],
       [1, 1, 2]])

In [53]:
arr1+arr2

array([[4, 3, 4],
       [4, 4, 2],
       [2, 3, 4]])

In [54]:
arr1-arr2

array([[ 0, -1,  0],
       [ 0,  0,  0],
       [ 0,  1,  0]])

In [55]:
arr1

array([[2, 1, 2],
       [2, 2, 1],
       [1, 2, 2]])

In [56]:
arr2

array([[2, 2, 2],
       [2, 2, 1],
       [1, 1, 2]])

In [57]:
arr1*arr2

array([[4, 2, 4],
       [4, 4, 1],
       [1, 2, 4]])

In [58]:
arr1/arr2

array([[1. , 0.5, 1. ],
       [1. , 1. , 1. ],
       [1. , 2. , 1. ]])

In [59]:
arr1/0

/tmp/ipykernel_600/1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [60]:
# Numpy : Broadcasting

In [61]:
arr = np.zeros((3,4))

In [62]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [63]:
arr+5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [64]:
a = np.array([1,2,3,4])

In [65]:
arr+a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [68]:
b = np.array([[3,4,5]])

In [70]:
arr+b.transpose()

array([[3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.]])