In [1]:
import numpy as np

In [2]:
#Numpy - Array Manipulation

In [5]:
arr = np.random.randint(1,10,(4,4))

In [6]:
arr

array([[5, 3, 7, 3],
       [3, 6, 9, 3],
       [9, 8, 3, 7],
       [4, 2, 2, 1]])

In [7]:
arr.reshape(8,2)

array([[5, 3],
       [7, 3],
       [3, 6],
       [9, 3],
       [9, 8],
       [3, 7],
       [4, 2],
       [2, 1]])

In [8]:
arr.T

array([[5, 3, 9, 4],
       [3, 6, 8, 2],
       [7, 9, 3, 2],
       [3, 3, 7, 1]])

In [9]:
arr.flatten()

array([5, 3, 7, 3, 3, 6, 9, 3, 9, 8, 3, 7, 4, 2, 2, 1])

In [10]:
arr

array([[5, 3, 7, 3],
       [3, 6, 9, 3],
       [9, 8, 3, 7],
       [4, 2, 2, 1]])

In [12]:
np.expand_dims(arr,axis = 1)

array([[[5, 3, 7, 3]],

       [[3, 6, 9, 3]],

       [[9, 8, 3, 7]],

       [[4, 2, 2, 1]]])

In [13]:
np.expand_dims(arr,axis = 0)

array([[[5, 3, 7, 3],
        [3, 6, 9, 3],
        [9, 8, 3, 7],
        [4, 2, 2, 1]]])

In [14]:
data = np.array([[1],[2],[3]])

In [15]:
data


array([[1],
       [2],
       [3]])

In [16]:
np.squeeze(data)

array([1, 2, 3])

In [17]:
np.repeat(data,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [19]:
np.roll(data,2)

array([[2],
       [3],
       [1]])

In [20]:
np.diag(np.array([1,2,3,4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [21]:
#Numpy - Binary Operations

In [22]:
arr1 = np.random.randint(1,10,(3,4))
arr2 = np.random.randint(1,10,(3,4))

In [23]:
arr1

array([[5, 6, 1, 3],
       [8, 2, 4, 1],
       [3, 2, 1, 7]])

In [24]:
arr2

array([[4, 1, 1, 9],
       [1, 1, 6, 7],
       [5, 9, 7, 7]])

In [25]:
arr1+arr2

array([[ 9,  7,  2, 12],
       [ 9,  3, 10,  8],
       [ 8, 11,  8, 14]])

In [26]:
arr1*arr2

array([[20,  6,  1, 27],
       [ 8,  2, 24,  7],
       [15, 18,  7, 49]])

In [27]:
arr1/arr2

array([[1.25      , 6.        , 1.        , 0.33333333],
       [8.        , 2.        , 0.66666667, 0.14285714],
       [0.6       , 0.22222222, 0.14285714, 1.        ]])

In [28]:
arr1-arr2

array([[ 1,  5,  0, -6],
       [ 7,  1, -2, -6],
       [-2, -7, -6,  0]])

In [29]:
arr1**arr2

array([[   625,      6,      1,  19683],
       [     8,      2,   4096,      1],
       [   243,    512,      1, 823543]])

In [30]:
~arr1

array([[-6, -7, -2, -4],
       [-9, -3, -5, -2],
       [-4, -3, -2, -8]])

In [31]:
~arr2

array([[ -5,  -2,  -2, -10],
       [ -2,  -2,  -7,  -8],
       [ -6, -10,  -8,  -8]])

In [32]:
arr1>arr2

array([[ True,  True, False, False],
       [ True,  True, False, False],
       [False, False, False, False]])

In [33]:
arr2>arr1

array([[False, False, False,  True],
       [False, False,  True,  True],
       [ True,  True,  True, False]])

In [34]:
# Numpy - String Operations

In [35]:
arr = np.array(['hello','world'])

In [36]:
arr

array(['hello', 'world'], dtype='<U5')

In [37]:
np.char.upper(arr)

array(['HELLO', 'WORLD'], dtype='<U5')

In [38]:
np.char.capitalize(arr)

array(['Hello', 'World'], dtype='<U5')

In [39]:
np.char.title(arr)

array(['Hello', 'World'], dtype='<U5')

In [40]:
#Numpy - Mathematical Functions

In [41]:
np.sin(arr1)

array([[-0.95892427, -0.2794155 ,  0.84147098,  0.14112001],
       [ 0.98935825,  0.90929743, -0.7568025 ,  0.84147098],
       [ 0.14112001,  0.90929743,  0.84147098,  0.6569866 ]])

In [42]:
np.cos(arr1)

array([[ 0.28366219,  0.96017029,  0.54030231, -0.9899925 ],
       [-0.14550003, -0.41614684, -0.65364362,  0.54030231],
       [-0.9899925 , -0.41614684,  0.54030231,  0.75390225]])

In [43]:
arr1

array([[5, 6, 1, 3],
       [8, 2, 4, 1],
       [3, 2, 1, 7]])

In [44]:
np.exp(arr1)

array([[1.48413159e+02, 4.03428793e+02, 2.71828183e+00, 2.00855369e+01],
       [2.98095799e+03, 7.38905610e+00, 5.45981500e+01, 2.71828183e+00],
       [2.00855369e+01, 7.38905610e+00, 2.71828183e+00, 1.09663316e+03]])

In [45]:
np.power(arr1,2)

array([[25, 36,  1,  9],
       [64,  4, 16,  1],
       [ 9,  4,  1, 49]])

In [46]:
np.mean(arr1)

3.5833333333333335

In [47]:
np.median(arr1)

3.0

In [48]:
np.mode(arr1)

AttributeError: module 'numpy' has no attribute 'mode'

In [49]:
np.std(arr1)

2.32588095615881

In [50]:
np.var(arr1)

5.409722222222221

In [51]:
np.min(arr1)

1

In [52]:
np.max(arr1)

8

In [53]:
#Numpy - Arithmetic Operations

In [54]:
arr1

array([[5, 6, 1, 3],
       [8, 2, 4, 1],
       [3, 2, 1, 7]])

In [55]:
arr2

array([[4, 1, 1, 9],
       [1, 1, 6, 7],
       [5, 9, 7, 7]])

In [56]:
arr1-arr2

array([[ 1,  5,  0, -6],
       [ 7,  1, -2, -6],
       [-2, -7, -6,  0]])

In [57]:
np.subtract(arr1,arr2)

array([[ 1,  5,  0, -6],
       [ 7,  1, -2, -6],
       [-2, -7, -6,  0]])

In [58]:
np.multiply(arr1,arr2)

array([[20,  6,  1, 27],
       [ 8,  2, 24,  7],
       [15, 18,  7, 49]])

In [59]:
np.mod(arr1,arr2)

array([[1, 0, 0, 3],
       [0, 0, 4, 1],
       [3, 2, 1, 0]])

In [60]:
np.power(arr1,arr2)

array([[   625,      6,      1,  19683],
       [     8,      2,   4096,      1],
       [   243,    512,      1, 823543]])

In [ ]:
np.sqrt()