In [1]:
#Sort,Search & Counting Functions

In [2]:
import numpy as np

In [15]:
arr = np.array([5,3,2,7,5,2])

In [16]:
arr

array([5, 3, 2, 7, 5, 2])

In [17]:
np.sort(arr)

array([2, 2, 3, 5, 5, 7])

In [18]:
np.searchsorted(arr,6)

3

In [22]:
arr1 = np.array([0,3,6,3,6,8,4,0,0,0,0,4,3,23,5,])

In [23]:
np.count_nonzero(arr1)

10

In [24]:
np.where(arr1 > 0)

(array([ 1,  2,  3,  4,  5,  6, 11, 12, 13, 14]),)

In [26]:
np.extract(arr1 > 2,arr1)

array([ 3,  6,  3,  6,  8,  4,  4,  3, 23,  5])

In [27]:
# Numpy - Byte Swapping

In [28]:
arr1

array([ 0,  3,  6,  3,  6,  8,  4,  0,  0,  0,  0,  4,  3, 23,  5])

In [31]:
arr.byteswap(True)

array([360287970189639680, 216172782113783808, 144115188075855872,
       504403158265495552, 360287970189639680, 144115188075855872])

In [32]:
arr

array([360287970189639680, 216172782113783808, 144115188075855872,
       504403158265495552, 360287970189639680, 144115188075855872])

In [33]:
# Numpy - Copies & Views

In [34]:
arr

array([360287970189639680, 216172782113783808, 144115188075855872,
       504403158265495552, 360287970189639680, 144115188075855872])

In [35]:
arr1

array([ 0,  3,  6,  3,  6,  8,  4,  0,  0,  0,  0,  4,  3, 23,  5])

In [36]:
a = np.copy(arr1)

In [37]:
a

array([ 0,  3,  6,  3,  6,  8,  4,  0,  0,  0,  0,  4,  3, 23,  5])

In [38]:
b = arr1.view()

In [39]:
b

array([ 0,  3,  6,  3,  6,  8,  4,  0,  0,  0,  0,  4,  3, 23,  5])

In [40]:
b[0] = 234

In [41]:
b

array([234,   3,   6,   3,   6,   8,   4,   0,   0,   0,   0,   4,   3,
        23,   5])

In [42]:
arr1

array([234,   3,   6,   3,   6,   8,   4,   0,   0,   0,   0,   4,   3,
        23,   5])

In [43]:
# Numpy - Matrix Library

In [44]:
import numpy.matlib as nm

In [46]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [47]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [48]:
nm.eye(4)

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [50]:
#Numpy - Linear Algebra

In [53]:
arr1 = np.random.randint([[2,3],[4,5]])

In [54]:
arr2 = np.random.randint([[5,3],[2,5]])

In [55]:
arr1

array([[0, 0],
       [0, 3]])

In [56]:
arr2

array([[1, 1],
       [0, 0]])

In [ ]:
np.dot(arr1,arr2)